# Generated by Django 4.2.6 on 2023-10-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='xu',
            field=models.CharField(default='Your Default Author', max_length=255),
        ),
    ]
