# Generated by Django 4.2.6 on 2023-10-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_article_xu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='xu',
            field=models.CharField(default=-1, max_length=255),
        ),
    ]
