# Generated by Django 4.2.6 on 2023-10-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_article_xu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='xu',
            field=models.PositiveIntegerField(),
        ),
    ]
